### PR TITLE
Fix #15

### LINKED ISSUE #15: when destroy,rails "URI::InvalidURIError: URI must be ascii only"
are you Chinese? if not please view below:
[https://github.com/thoughtbot/paperclip/issues/2286#issuecomment-241943471](more bug messages)

当我用阿里云，并且文件名为中文时，destroy会报错，当我把paperclip-aliyun-configuration删除后，重启项目，文件改为本地存储，这时destroy不会报错，请问此问题应该怎么解决？

### PR DESCRIPTION
**Pull request by Martin91**

### CODE REVIEW

**Comment by aidistan** [comment]
Shall we release a new minor version?

**Comment by Martin91** [comment]
@aidistan yes, doing now!

**Comment by Martin91** [comment]
@aidistan Have released [v0.1.1](https://rubygems.org/gems/paperclip-storage-aliyun/versions/0.1.1) . Thanks for your great job before!

**Comment by aidistan** [comment]
Haven't pushed the latest commit here? I found the version number in master branch was still `0.1.0`.

**Comment by Martin288** [comment]
@aidistan sorry, forgot to push the latest commit, but I did push the latest release last night, https://github.com/Martin91/paperclip-storage-aliyun/releases Will push code to master branch tonight.

**Pull request merged**
